[package]
name = "_socha"
version = "3.4.0"
edition = "2021"

[lib]
name = "socha"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2" }
pyo3-log = "0.11.0"
log = "0.4.20"
itertools = "0.13.0"

[features]
extension-module = ["pyo3/extension-module"]
