[package]
name = "_socha"
version = "4.3.9"
edition = "2021"

[lib]
name = "socha"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module"] }
pyo3-log = "0.13.2"
log = "0.4.20"
itertools = "0.13.0"

[features]
extension-module = ["pyo3/extension-module"]
