name: convert readme
on:
  push:
    branches: [ master ]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: convert to rst
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
          sudo dpkg -i pandoc-2.19.2-1-amd64.deb
          pandoc README.md --from markdown -f gfm --to rst -s -o docs/index.rst
          cat docs/appending >> docs/index.rst
      - name: commit index.rst
        run: |
          git config --global user.name 'Falcon'
          git config --global user.email 'stu222782@mail.uni-kiel.de'
          git add docs/index.rst
          git commit -m "docs: auto update index.rst"
          git push
        continue-on-error: true